[ fix ] handling of `VCase` in `Core.Case.Builder.sameType`
Current implementation of `headEq` inside `Core.Case.Builder.sameType`
considers two `VCase`s to always be different. Because of this, the
following example fails to compile.

```idris
module Main

public export
record X (flag : Bool) where
  constructor MkX
  x : if flag then Bool else Void

f : X True -> ()
f (MkX True) = ()
f (MkX False) = ()
```

Instead, the following compilation error is produced:

```
Error: Patterns for f require matching on different types.

Main:13:1--13:18
 09 |   constructor MkX
 10 |   x : if flag then Bool else Void
 11 |
 12 | f : X True -> ()
 13 | f (MkX True) = ()
      ^^^^^^^^^^^^^^^^^
```

This patch changes the behaviour of `headEq` to make it treat `VCase`s
as equal, eliminating the error.